// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protocol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControllerInfo struct {
	PortName             string   `protobuf:"bytes,1,opt,name=portName,proto3" json:"portName,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerInfo) Reset()         { *m = ControllerInfo{} }
func (m *ControllerInfo) String() string { return proto.CompactTextString(m) }
func (*ControllerInfo) ProtoMessage()    {}
func (*ControllerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{0}
}
func (m *ControllerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerInfo.Unmarshal(m, b)
}
func (m *ControllerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerInfo.Marshal(b, m, deterministic)
}
func (dst *ControllerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerInfo.Merge(dst, src)
}
func (m *ControllerInfo) XXX_Size() int {
	return xxx_messageInfo_ControllerInfo.Size(m)
}
func (m *ControllerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerInfo proto.InternalMessageInfo

func (m *ControllerInfo) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

func (m *ControllerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ControllerListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerListRequest) Reset()         { *m = ControllerListRequest{} }
func (m *ControllerListRequest) String() string { return proto.CompactTextString(m) }
func (*ControllerListRequest) ProtoMessage()    {}
func (*ControllerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{1}
}
func (m *ControllerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerListRequest.Unmarshal(m, b)
}
func (m *ControllerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerListRequest.Marshal(b, m, deterministic)
}
func (dst *ControllerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerListRequest.Merge(dst, src)
}
func (m *ControllerListRequest) XXX_Size() int {
	return xxx_messageInfo_ControllerListRequest.Size(m)
}
func (m *ControllerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerListRequest proto.InternalMessageInfo

type ControllerListResponse struct {
	ControllerInfos      []*ControllerInfo `protobuf:"bytes,1,rep,name=controller_infos,json=controllerInfos,proto3" json:"controller_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ControllerListResponse) Reset()         { *m = ControllerListResponse{} }
func (m *ControllerListResponse) String() string { return proto.CompactTextString(m) }
func (*ControllerListResponse) ProtoMessage()    {}
func (*ControllerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{2}
}
func (m *ControllerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerListResponse.Unmarshal(m, b)
}
func (m *ControllerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerListResponse.Marshal(b, m, deterministic)
}
func (dst *ControllerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerListResponse.Merge(dst, src)
}
func (m *ControllerListResponse) XXX_Size() int {
	return xxx_messageInfo_ControllerListResponse.Size(m)
}
func (m *ControllerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerListResponse proto.InternalMessageInfo

func (m *ControllerListResponse) GetControllerInfos() []*ControllerInfo {
	if m != nil {
		return m.ControllerInfos
	}
	return nil
}

type ReadControllerOutputRequest struct {
	ControllerPortName   string   `protobuf:"bytes,1,opt,name=controller_port_name,json=controllerPortName,proto3" json:"controller_port_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadControllerOutputRequest) Reset()         { *m = ReadControllerOutputRequest{} }
func (m *ReadControllerOutputRequest) String() string { return proto.CompactTextString(m) }
func (*ReadControllerOutputRequest) ProtoMessage()    {}
func (*ReadControllerOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{3}
}
func (m *ReadControllerOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadControllerOutputRequest.Unmarshal(m, b)
}
func (m *ReadControllerOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadControllerOutputRequest.Marshal(b, m, deterministic)
}
func (dst *ReadControllerOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadControllerOutputRequest.Merge(dst, src)
}
func (m *ReadControllerOutputRequest) XXX_Size() int {
	return xxx_messageInfo_ReadControllerOutputRequest.Size(m)
}
func (m *ReadControllerOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadControllerOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadControllerOutputRequest proto.InternalMessageInfo

func (m *ReadControllerOutputRequest) GetControllerPortName() string {
	if m != nil {
		return m.ControllerPortName
	}
	return ""
}

type ReadControllerOutputResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadControllerOutputResponse) Reset()         { *m = ReadControllerOutputResponse{} }
func (m *ReadControllerOutputResponse) String() string { return proto.CompactTextString(m) }
func (*ReadControllerOutputResponse) ProtoMessage()    {}
func (*ReadControllerOutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{4}
}
func (m *ReadControllerOutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadControllerOutputResponse.Unmarshal(m, b)
}
func (m *ReadControllerOutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadControllerOutputResponse.Marshal(b, m, deterministic)
}
func (dst *ReadControllerOutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadControllerOutputResponse.Merge(dst, src)
}
func (m *ReadControllerOutputResponse) XXX_Size() int {
	return xxx_messageInfo_ReadControllerOutputResponse.Size(m)
}
func (m *ReadControllerOutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadControllerOutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadControllerOutputResponse proto.InternalMessageInfo

func (m *ReadControllerOutputResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type FlashControllerRequest struct {
	ControllerPortName   string   `protobuf:"bytes,1,opt,name=controller_port_name,json=controllerPortName,proto3" json:"controller_port_name,omitempty"`
	HexFileContent       []byte   `protobuf:"bytes,2,opt,name=hex_file_content,json=hexFileContent,proto3" json:"hex_file_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashControllerRequest) Reset()         { *m = FlashControllerRequest{} }
func (m *FlashControllerRequest) String() string { return proto.CompactTextString(m) }
func (*FlashControllerRequest) ProtoMessage()    {}
func (*FlashControllerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{5}
}
func (m *FlashControllerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashControllerRequest.Unmarshal(m, b)
}
func (m *FlashControllerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashControllerRequest.Marshal(b, m, deterministic)
}
func (dst *FlashControllerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashControllerRequest.Merge(dst, src)
}
func (m *FlashControllerRequest) XXX_Size() int {
	return xxx_messageInfo_FlashControllerRequest.Size(m)
}
func (m *FlashControllerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashControllerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FlashControllerRequest proto.InternalMessageInfo

func (m *FlashControllerRequest) GetControllerPortName() string {
	if m != nil {
		return m.ControllerPortName
	}
	return ""
}

func (m *FlashControllerRequest) GetHexFileContent() []byte {
	if m != nil {
		return m.HexFileContent
	}
	return nil
}

type FlashControllerResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlashControllerResponse) Reset()         { *m = FlashControllerResponse{} }
func (m *FlashControllerResponse) String() string { return proto.CompactTextString(m) }
func (*FlashControllerResponse) ProtoMessage()    {}
func (*FlashControllerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{6}
}
func (m *FlashControllerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlashControllerResponse.Unmarshal(m, b)
}
func (m *FlashControllerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlashControllerResponse.Marshal(b, m, deterministic)
}
func (dst *FlashControllerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlashControllerResponse.Merge(dst, src)
}
func (m *FlashControllerResponse) XXX_Size() int {
	return xxx_messageInfo_FlashControllerResponse.Size(m)
}
func (m *FlashControllerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FlashControllerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FlashControllerResponse proto.InternalMessageInfo

func (m *FlashControllerResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type ResetUsbRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetUsbRequest) Reset()         { *m = ResetUsbRequest{} }
func (m *ResetUsbRequest) String() string { return proto.CompactTextString(m) }
func (*ResetUsbRequest) ProtoMessage()    {}
func (*ResetUsbRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{7}
}
func (m *ResetUsbRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUsbRequest.Unmarshal(m, b)
}
func (m *ResetUsbRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUsbRequest.Marshal(b, m, deterministic)
}
func (dst *ResetUsbRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUsbRequest.Merge(dst, src)
}
func (m *ResetUsbRequest) XXX_Size() int {
	return xxx_messageInfo_ResetUsbRequest.Size(m)
}
func (m *ResetUsbRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUsbRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUsbRequest proto.InternalMessageInfo

type ResetUsbResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetUsbResponse) Reset()         { *m = ResetUsbResponse{} }
func (m *ResetUsbResponse) String() string { return proto.CompactTextString(m) }
func (*ResetUsbResponse) ProtoMessage()    {}
func (*ResetUsbResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{8}
}
func (m *ResetUsbResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetUsbResponse.Unmarshal(m, b)
}
func (m *ResetUsbResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetUsbResponse.Marshal(b, m, deterministic)
}
func (dst *ResetUsbResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetUsbResponse.Merge(dst, src)
}
func (m *ResetUsbResponse) XXX_Size() int {
	return xxx_messageInfo_ResetUsbResponse.Size(m)
}
func (m *ResetUsbResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetUsbResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetUsbResponse proto.InternalMessageInfo

func (m *ResetUsbResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type WriteToControllerRequest struct {
	ControllerPortName   string   `protobuf:"bytes,1,opt,name=controller_port_name,json=controllerPortName,proto3" json:"controller_port_name,omitempty"`
	Message              []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteToControllerRequest) Reset()         { *m = WriteToControllerRequest{} }
func (m *WriteToControllerRequest) String() string { return proto.CompactTextString(m) }
func (*WriteToControllerRequest) ProtoMessage()    {}
func (*WriteToControllerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{9}
}
func (m *WriteToControllerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteToControllerRequest.Unmarshal(m, b)
}
func (m *WriteToControllerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteToControllerRequest.Marshal(b, m, deterministic)
}
func (dst *WriteToControllerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteToControllerRequest.Merge(dst, src)
}
func (m *WriteToControllerRequest) XXX_Size() int {
	return xxx_messageInfo_WriteToControllerRequest.Size(m)
}
func (m *WriteToControllerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteToControllerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteToControllerRequest proto.InternalMessageInfo

func (m *WriteToControllerRequest) GetControllerPortName() string {
	if m != nil {
		return m.ControllerPortName
	}
	return ""
}

func (m *WriteToControllerRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type WriteToControllerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteToControllerResponse) Reset()         { *m = WriteToControllerResponse{} }
func (m *WriteToControllerResponse) String() string { return proto.CompactTextString(m) }
func (*WriteToControllerResponse) ProtoMessage()    {}
func (*WriteToControllerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_1506643d300dc955, []int{10}
}
func (m *WriteToControllerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteToControllerResponse.Unmarshal(m, b)
}
func (m *WriteToControllerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteToControllerResponse.Marshal(b, m, deterministic)
}
func (dst *WriteToControllerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteToControllerResponse.Merge(dst, src)
}
func (m *WriteToControllerResponse) XXX_Size() int {
	return xxx_messageInfo_WriteToControllerResponse.Size(m)
}
func (m *WriteToControllerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteToControllerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteToControllerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ControllerInfo)(nil), "proto.ControllerInfo")
	proto.RegisterType((*ControllerListRequest)(nil), "proto.ControllerListRequest")
	proto.RegisterType((*ControllerListResponse)(nil), "proto.ControllerListResponse")
	proto.RegisterType((*ReadControllerOutputRequest)(nil), "proto.ReadControllerOutputRequest")
	proto.RegisterType((*ReadControllerOutputResponse)(nil), "proto.ReadControllerOutputResponse")
	proto.RegisterType((*FlashControllerRequest)(nil), "proto.FlashControllerRequest")
	proto.RegisterType((*FlashControllerResponse)(nil), "proto.FlashControllerResponse")
	proto.RegisterType((*ResetUsbRequest)(nil), "proto.ResetUsbRequest")
	proto.RegisterType((*ResetUsbResponse)(nil), "proto.ResetUsbResponse")
	proto.RegisterType((*WriteToControllerRequest)(nil), "proto.WriteToControllerRequest")
	proto.RegisterType((*WriteToControllerResponse)(nil), "proto.WriteToControllerResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NervoServiceClient is the client API for NervoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NervoServiceClient interface {
	ListControllers(ctx context.Context, in *ControllerListRequest, opts ...grpc.CallOption) (*ControllerListResponse, error)
	ReadControllerOutput(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (*ReadControllerOutputResponse, error)
	FlashController(ctx context.Context, in *FlashControllerRequest, opts ...grpc.CallOption) (*FlashControllerResponse, error)
	ReadControllerOutputContinuously(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (NervoService_ReadControllerOutputContinuouslyClient, error)
	SetControllerName(ctx context.Context, in *ControllerInfo, opts ...grpc.CallOption) (*ControllerListResponse, error)
	ResetUsb(ctx context.Context, in *ResetUsbRequest, opts ...grpc.CallOption) (*ResetUsbResponse, error)
	WriteToController(ctx context.Context, in *WriteToControllerRequest, opts ...grpc.CallOption) (*WriteToControllerResponse, error)
}

type nervoServiceClient struct {
	cc *grpc.ClientConn
}

func NewNervoServiceClient(cc *grpc.ClientConn) NervoServiceClient {
	return &nervoServiceClient{cc}
}

func (c *nervoServiceClient) ListControllers(ctx context.Context, in *ControllerListRequest, opts ...grpc.CallOption) (*ControllerListResponse, error) {
	out := new(ControllerListResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/ListControllers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) ReadControllerOutput(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (*ReadControllerOutputResponse, error) {
	out := new(ReadControllerOutputResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/ReadControllerOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) FlashController(ctx context.Context, in *FlashControllerRequest, opts ...grpc.CallOption) (*FlashControllerResponse, error) {
	out := new(FlashControllerResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/FlashController", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) ReadControllerOutputContinuously(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (NervoService_ReadControllerOutputContinuouslyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NervoService_serviceDesc.Streams[0], "/proto.NervoService/ReadControllerOutputContinuously", opts...)
	if err != nil {
		return nil, err
	}
	x := &nervoServiceReadControllerOutputContinuouslyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NervoService_ReadControllerOutputContinuouslyClient interface {
	Recv() (*ReadControllerOutputResponse, error)
	grpc.ClientStream
}

type nervoServiceReadControllerOutputContinuouslyClient struct {
	grpc.ClientStream
}

func (x *nervoServiceReadControllerOutputContinuouslyClient) Recv() (*ReadControllerOutputResponse, error) {
	m := new(ReadControllerOutputResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nervoServiceClient) SetControllerName(ctx context.Context, in *ControllerInfo, opts ...grpc.CallOption) (*ControllerListResponse, error) {
	out := new(ControllerListResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/SetControllerName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) ResetUsb(ctx context.Context, in *ResetUsbRequest, opts ...grpc.CallOption) (*ResetUsbResponse, error) {
	out := new(ResetUsbResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/ResetUsb", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) WriteToController(ctx context.Context, in *WriteToControllerRequest, opts ...grpc.CallOption) (*WriteToControllerResponse, error) {
	out := new(WriteToControllerResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/WriteToController", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NervoServiceServer is the server API for NervoService service.
type NervoServiceServer interface {
	ListControllers(context.Context, *ControllerListRequest) (*ControllerListResponse, error)
	ReadControllerOutput(context.Context, *ReadControllerOutputRequest) (*ReadControllerOutputResponse, error)
	FlashController(context.Context, *FlashControllerRequest) (*FlashControllerResponse, error)
	ReadControllerOutputContinuously(*ReadControllerOutputRequest, NervoService_ReadControllerOutputContinuouslyServer) error
	SetControllerName(context.Context, *ControllerInfo) (*ControllerListResponse, error)
	ResetUsb(context.Context, *ResetUsbRequest) (*ResetUsbResponse, error)
	WriteToController(context.Context, *WriteToControllerRequest) (*WriteToControllerResponse, error)
}

func RegisterNervoServiceServer(s *grpc.Server, srv NervoServiceServer) {
	s.RegisterService(&_NervoService_serviceDesc, srv)
}

func _NervoService_ListControllers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).ListControllers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/ListControllers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).ListControllers(ctx, req.(*ControllerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_ReadControllerOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadControllerOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).ReadControllerOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/ReadControllerOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).ReadControllerOutput(ctx, req.(*ReadControllerOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_FlashController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlashControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).FlashController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/FlashController",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).FlashController(ctx, req.(*FlashControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_ReadControllerOutputContinuously_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadControllerOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NervoServiceServer).ReadControllerOutputContinuously(m, &nervoServiceReadControllerOutputContinuouslyServer{stream})
}

type NervoService_ReadControllerOutputContinuouslyServer interface {
	Send(*ReadControllerOutputResponse) error
	grpc.ServerStream
}

type nervoServiceReadControllerOutputContinuouslyServer struct {
	grpc.ServerStream
}

func (x *nervoServiceReadControllerOutputContinuouslyServer) Send(m *ReadControllerOutputResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NervoService_SetControllerName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).SetControllerName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/SetControllerName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).SetControllerName(ctx, req.(*ControllerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_ResetUsb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUsbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).ResetUsb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/ResetUsb",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).ResetUsb(ctx, req.(*ResetUsbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_WriteToController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteToControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).WriteToController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/WriteToController",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).WriteToController(ctx, req.(*WriteToControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NervoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NervoService",
	HandlerType: (*NervoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListControllers",
			Handler:    _NervoService_ListControllers_Handler,
		},
		{
			MethodName: "ReadControllerOutput",
			Handler:    _NervoService_ReadControllerOutput_Handler,
		},
		{
			MethodName: "FlashController",
			Handler:    _NervoService_FlashController_Handler,
		},
		{
			MethodName: "SetControllerName",
			Handler:    _NervoService_SetControllerName_Handler,
		},
		{
			MethodName: "ResetUsb",
			Handler:    _NervoService_ResetUsb_Handler,
		},
		{
			MethodName: "WriteToController",
			Handler:    _NervoService_WriteToController_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadControllerOutputContinuously",
			Handler:       _NervoService_ReadControllerOutputContinuously_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/protocol.proto",
}

func init() { proto.RegisterFile("proto/protocol.proto", fileDescriptor_protocol_1506643d300dc955) }

var fileDescriptor_protocol_1506643d300dc955 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xa1, 0x94, 0x32, 0x54, 0x75, 0xb2, 0x4a, 0x1d, 0xe3, 0x16, 0xb0, 0x96, 0x4b, 0xc4,
	0xa1, 0x94, 0x22, 0x71, 0xe1, 0x52, 0xa9, 0x52, 0xa5, 0x4a, 0x28, 0xad, 0x5c, 0x3e, 0x24, 0x2e,
	0x96, 0x6b, 0xc6, 0xc4, 0x92, 0xb3, 0x6b, 0xbc, 0xeb, 0x28, 0xfc, 0x5b, 0x7e, 0x0a, 0xf2, 0x7a,
	0x1d, 0x27, 0xb1, 0x9d, 0x48, 0x28, 0x97, 0x64, 0x67, 0xe6, 0xcd, 0xbc, 0x37, 0xbb, 0xcf, 0x30,
	0x48, 0x33, 0x2e, 0xf9, 0x3b, 0xf5, 0x1b, 0xf2, 0xe4, 0x4c, 0x1d, 0xc8, 0x13, 0xf5, 0x47, 0x2f,
	0xe1, 0xe8, 0x8a, 0x33, 0x99, 0xf1, 0x24, 0xc1, 0xec, 0x86, 0x45, 0x9c, 0x38, 0x70, 0x90, 0xf2,
	0x4c, 0x8e, 0x83, 0x29, 0xda, 0x86, 0x6b, 0x8c, 0x9e, 0x79, 0x8b, 0x98, 0x10, 0xd8, 0x63, 0x45,
	0xfe, 0x91, 0xca, 0xab, 0x33, 0x1d, 0xc2, 0x71, 0x3d, 0xe1, 0x73, 0x2c, 0xa4, 0x87, 0xbf, 0x73,
	0x14, 0x92, 0xfe, 0x00, 0x6b, 0xbd, 0x20, 0x52, 0xce, 0x04, 0x92, 0x4b, 0xe8, 0x85, 0x8b, 0x8a,
	0x1f, 0xb3, 0x88, 0x0b, 0xdb, 0x70, 0x1f, 0x8f, 0x9e, 0x5f, 0x1c, 0x97, 0xea, 0xce, 0x56, 0x35,
	0x79, 0x66, 0xb8, 0x12, 0x0b, 0x7a, 0x0b, 0x27, 0x1e, 0x06, 0x3f, 0x6b, 0xd8, 0x6d, 0x2e, 0xd3,
	0xbc, 0xa2, 0x26, 0xe7, 0x30, 0x58, 0x22, 0x28, 0xe4, 0xfb, 0xac, 0xde, 0x87, 0xd4, 0xb5, 0x3b,
	0xbd, 0x19, 0xfd, 0x08, 0xa7, 0xed, 0x03, 0xb5, 0x64, 0x0b, 0xf6, 0xb9, 0xca, 0xe8, 0x19, 0x3a,
	0xa2, 0x12, 0xac, 0xeb, 0x24, 0x10, 0x93, 0xba, 0xf1, 0xbf, 0x35, 0x90, 0x11, 0xf4, 0x26, 0x38,
	0xf7, 0xa3, 0x38, 0x41, 0xbf, 0x28, 0x23, 0x93, 0xea, 0xa6, 0x0f, 0xbd, 0xa3, 0x09, 0xce, 0xaf,
	0xe3, 0x04, 0xaf, 0xca, 0x2c, 0x7d, 0x0f, 0xc3, 0x06, 0xeb, 0x16, 0xa1, 0x7d, 0x30, 0x3d, 0x14,
	0x28, 0xbf, 0x8a, 0x87, 0xea, 0x81, 0xde, 0x42, 0xaf, 0x4e, 0x6d, 0x69, 0x8f, 0xc0, 0xfe, 0x9e,
	0xc5, 0x12, 0xbf, 0xf0, 0x5d, 0x6c, 0x6a, 0xc3, 0xd3, 0x29, 0x0a, 0x11, 0xfc, 0x42, 0xbd, 0x60,
	0x15, 0xd2, 0x13, 0x78, 0xd1, 0xc2, 0x53, 0x8a, 0xbb, 0xf8, 0xbb, 0x07, 0x87, 0x63, 0xcc, 0x66,
	0xfc, 0x1e, 0xb3, 0x59, 0x1c, 0x22, 0x19, 0x83, 0x59, 0x18, 0xab, 0x86, 0x0a, 0x72, 0xda, 0x70,
	0xd0, 0x92, 0x27, 0x9d, 0x97, 0x1d, 0x55, 0xbd, 0xbd, 0x0f, 0x83, 0x36, 0x17, 0x10, 0xaa, 0xdb,
	0x36, 0x78, 0xce, 0x79, 0xb3, 0x11, 0xa3, 0x09, 0xee, 0xc0, 0x5c, 0x7b, 0x38, 0x52, 0x49, 0x6a,
	0xb7, 0x91, 0xf3, 0xaa, 0xab, 0xac, 0x27, 0x4e, 0xc1, 0x6d, 0x63, 0x2c, 0xe2, 0x98, 0xe5, 0x3c,
	0x17, 0xc9, 0x9f, 0x9d, 0xc9, 0x3f, 0x37, 0xc8, 0x0d, 0xf4, 0xef, 0x71, 0xe9, 0xc2, 0xd5, 0x73,
	0xb6, 0x7f, 0xb5, 0xdb, 0x2e, 0xfb, 0x13, 0x1c, 0x54, 0xf6, 0x23, 0xd6, 0x82, 0x7d, 0xc5, 0xa2,
	0xce, 0xb0, 0x91, 0xd7, 0xcd, 0xdf, 0xa0, 0xdf, 0xf0, 0x09, 0x79, 0xad, 0xd1, 0x5d, 0x4e, 0x75,
	0xdc, 0x6e, 0x40, 0x39, 0xf7, 0x61, 0x5f, 0x01, 0x3e, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x37, 0x5d, 0x28, 0x35, 0x05, 0x00, 0x00,
}
