// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protocol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ControllerInfo struct {
	PortName             string   `protobuf:"bytes,1,opt,name=portName,proto3" json:"portName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerInfo) Reset()         { *m = ControllerInfo{} }
func (m *ControllerInfo) String() string { return proto.CompactTextString(m) }
func (*ControllerInfo) ProtoMessage()    {}
func (*ControllerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_ae2c0ea02935b1c2, []int{0}
}
func (m *ControllerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerInfo.Unmarshal(m, b)
}
func (m *ControllerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerInfo.Marshal(b, m, deterministic)
}
func (dst *ControllerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerInfo.Merge(dst, src)
}
func (m *ControllerInfo) XXX_Size() int {
	return xxx_messageInfo_ControllerInfo.Size(m)
}
func (m *ControllerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerInfo proto.InternalMessageInfo

func (m *ControllerInfo) GetPortName() string {
	if m != nil {
		return m.PortName
	}
	return ""
}

type ControllerListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerListRequest) Reset()         { *m = ControllerListRequest{} }
func (m *ControllerListRequest) String() string { return proto.CompactTextString(m) }
func (*ControllerListRequest) ProtoMessage()    {}
func (*ControllerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_ae2c0ea02935b1c2, []int{1}
}
func (m *ControllerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerListRequest.Unmarshal(m, b)
}
func (m *ControllerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerListRequest.Marshal(b, m, deterministic)
}
func (dst *ControllerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerListRequest.Merge(dst, src)
}
func (m *ControllerListRequest) XXX_Size() int {
	return xxx_messageInfo_ControllerListRequest.Size(m)
}
func (m *ControllerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerListRequest proto.InternalMessageInfo

type ControllerListResponse struct {
	ControllerInfos      []*ControllerInfo `protobuf:"bytes,1,rep,name=controller_infos,json=controllerInfos,proto3" json:"controller_infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ControllerListResponse) Reset()         { *m = ControllerListResponse{} }
func (m *ControllerListResponse) String() string { return proto.CompactTextString(m) }
func (*ControllerListResponse) ProtoMessage()    {}
func (*ControllerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_ae2c0ea02935b1c2, []int{2}
}
func (m *ControllerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerListResponse.Unmarshal(m, b)
}
func (m *ControllerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerListResponse.Marshal(b, m, deterministic)
}
func (dst *ControllerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerListResponse.Merge(dst, src)
}
func (m *ControllerListResponse) XXX_Size() int {
	return xxx_messageInfo_ControllerListResponse.Size(m)
}
func (m *ControllerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerListResponse proto.InternalMessageInfo

func (m *ControllerListResponse) GetControllerInfos() []*ControllerInfo {
	if m != nil {
		return m.ControllerInfos
	}
	return nil
}

type ReadControllerOutputRequest struct {
	ControllerPortName   string   `protobuf:"bytes,1,opt,name=controller_port_name,json=controllerPortName,proto3" json:"controller_port_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadControllerOutputRequest) Reset()         { *m = ReadControllerOutputRequest{} }
func (m *ReadControllerOutputRequest) String() string { return proto.CompactTextString(m) }
func (*ReadControllerOutputRequest) ProtoMessage()    {}
func (*ReadControllerOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_ae2c0ea02935b1c2, []int{3}
}
func (m *ReadControllerOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadControllerOutputRequest.Unmarshal(m, b)
}
func (m *ReadControllerOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadControllerOutputRequest.Marshal(b, m, deterministic)
}
func (dst *ReadControllerOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadControllerOutputRequest.Merge(dst, src)
}
func (m *ReadControllerOutputRequest) XXX_Size() int {
	return xxx_messageInfo_ReadControllerOutputRequest.Size(m)
}
func (m *ReadControllerOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadControllerOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadControllerOutputRequest proto.InternalMessageInfo

func (m *ReadControllerOutputRequest) GetControllerPortName() string {
	if m != nil {
		return m.ControllerPortName
	}
	return ""
}

type ReadControllerOutputResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadControllerOutputResponse) Reset()         { *m = ReadControllerOutputResponse{} }
func (m *ReadControllerOutputResponse) String() string { return proto.CompactTextString(m) }
func (*ReadControllerOutputResponse) ProtoMessage()    {}
func (*ReadControllerOutputResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_ae2c0ea02935b1c2, []int{4}
}
func (m *ReadControllerOutputResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadControllerOutputResponse.Unmarshal(m, b)
}
func (m *ReadControllerOutputResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadControllerOutputResponse.Marshal(b, m, deterministic)
}
func (dst *ReadControllerOutputResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadControllerOutputResponse.Merge(dst, src)
}
func (m *ReadControllerOutputResponse) XXX_Size() int {
	return xxx_messageInfo_ReadControllerOutputResponse.Size(m)
}
func (m *ReadControllerOutputResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadControllerOutputResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadControllerOutputResponse proto.InternalMessageInfo

func (m *ReadControllerOutputResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*ControllerInfo)(nil), "proto.ControllerInfo")
	proto.RegisterType((*ControllerListRequest)(nil), "proto.ControllerListRequest")
	proto.RegisterType((*ControllerListResponse)(nil), "proto.ControllerListResponse")
	proto.RegisterType((*ReadControllerOutputRequest)(nil), "proto.ReadControllerOutputRequest")
	proto.RegisterType((*ReadControllerOutputResponse)(nil), "proto.ReadControllerOutputResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NervoServiceClient is the client API for NervoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NervoServiceClient interface {
	ListControllers(ctx context.Context, in *ControllerListRequest, opts ...grpc.CallOption) (*ControllerListResponse, error)
	ReadControllerOutput(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (*ReadControllerOutputResponse, error)
}

type nervoServiceClient struct {
	cc *grpc.ClientConn
}

func NewNervoServiceClient(cc *grpc.ClientConn) NervoServiceClient {
	return &nervoServiceClient{cc}
}

func (c *nervoServiceClient) ListControllers(ctx context.Context, in *ControllerListRequest, opts ...grpc.CallOption) (*ControllerListResponse, error) {
	out := new(ControllerListResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/ListControllers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nervoServiceClient) ReadControllerOutput(ctx context.Context, in *ReadControllerOutputRequest, opts ...grpc.CallOption) (*ReadControllerOutputResponse, error) {
	out := new(ReadControllerOutputResponse)
	err := c.cc.Invoke(ctx, "/proto.NervoService/ReadControllerOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NervoServiceServer is the server API for NervoService service.
type NervoServiceServer interface {
	ListControllers(context.Context, *ControllerListRequest) (*ControllerListResponse, error)
	ReadControllerOutput(context.Context, *ReadControllerOutputRequest) (*ReadControllerOutputResponse, error)
}

func RegisterNervoServiceServer(s *grpc.Server, srv NervoServiceServer) {
	s.RegisterService(&_NervoService_serviceDesc, srv)
}

func _NervoService_ListControllers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).ListControllers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/ListControllers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).ListControllers(ctx, req.(*ControllerListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NervoService_ReadControllerOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadControllerOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NervoServiceServer).ReadControllerOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NervoService/ReadControllerOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NervoServiceServer).ReadControllerOutput(ctx, req.(*ReadControllerOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NervoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NervoService",
	HandlerType: (*NervoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListControllers",
			Handler:    _NervoService_ListControllers_Handler,
		},
		{
			MethodName: "ReadControllerOutput",
			Handler:    _NervoService_ReadControllerOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/protocol.proto",
}

func init() { proto.RegisterFile("proto/protocol.proto", fileDescriptor_protocol_ae2c0ea02935b1c2) }

var fileDescriptor_protocol_ae2c0ea02935b1c2 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0xc9, 0xf9, 0x39, 0x7a, 0x60, 0x86, 0x10, 0x2b, 0x98, 0x52, 0xd2, 0xe1,
	0xe2, 0x73, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0xf2, 0xcc, 0x4b, 0xcb, 0x17,
	0x92, 0xe2, 0xe2, 0x28, 0xc8, 0x2f, 0x2a, 0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0xf3, 0x95, 0xc4, 0xb9, 0x44, 0x11, 0xaa, 0x7d, 0x32, 0x8b, 0x4b, 0x82, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0xa2, 0xb8, 0xc4, 0xd0, 0x25, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x1c, 0xb8, 0x04, 0x92, 0xe1, 0x32, 0xf1, 0x99, 0x79, 0x69, 0xf9, 0xc5, 0x12, 0x8c,
	0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xa2, 0x10, 0x97, 0xe8, 0xa1, 0xda, 0x1f, 0xc4, 0x9f, 0x8c, 0xc2,
	0x2f, 0x56, 0xf2, 0xe7, 0x92, 0x0e, 0x4a, 0x4d, 0x4c, 0x41, 0x28, 0xf3, 0x2f, 0x2d, 0x29, 0x28,
	0x85, 0x59, 0x2d, 0x64, 0xc0, 0x25, 0x82, 0x64, 0x01, 0xc8, 0xa9, 0xf1, 0x79, 0x08, 0xb7, 0x0b,
	0x21, 0xe4, 0x02, 0x60, 0xbe, 0x30, 0xe3, 0x92, 0xc1, 0x6e, 0x20, 0xd4, 0xc9, 0x62, 0x5c, 0x6c,
	0xf9, 0x60, 0x11, 0xa8, 0x19, 0x50, 0x9e, 0xd1, 0x7e, 0x46, 0x2e, 0x1e, 0xbf, 0xd4, 0xa2, 0xb2,
	0xfc, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x3f, 0x2e, 0x7e, 0x90, 0x5f, 0x11, 0x06,
	0x15, 0x0b, 0xc9, 0x60, 0x78, 0x0a, 0x29, 0x98, 0xa4, 0x64, 0x71, 0xc8, 0x42, 0x2d, 0x8e, 0xe7,
	0x12, 0xc1, 0xe6, 0x30, 0x21, 0x25, 0xa8, 0x36, 0x3c, 0xc1, 0x20, 0xa5, 0x8c, 0x57, 0x0d, 0xc4,
	0x82, 0x24, 0x36, 0xb0, 0x1a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0xaf, 0x68, 0x39,
	0x13, 0x02, 0x00, 0x00,
}
